// <auto-generated />
using BarcodeScannerDatabaseImplement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarcodeScannerDatabaseImplement.Migrations
{
    [DbContext(typeof(BarcodeScannerDatabase))]
    [Migration("20241203124057_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BarcodeScannerDatabaseImplement.Models.BarcodeProduct", b =>
                {
                    b.Property<int>("Gtin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Gtin");

                    b.ToTable("BarcodeProducts");
                });

            modelBuilder.Entity("BarcodeScannerDatabaseImplement.Models.QrStuff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gtin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Gtin");

                    b.ToTable("QrStuffs");
                });

            modelBuilder.Entity("BarcodeScannerDatabaseImplement.Models.QrStuff", b =>
                {
                    b.HasOne("BarcodeScannerDatabaseImplement.Models.BarcodeProduct", "BarcodeProduct")
                        .WithMany("QrStuffs")
                        .HasForeignKey("Gtin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BarcodeProduct");
                });

            modelBuilder.Entity("BarcodeScannerDatabaseImplement.Models.BarcodeProduct", b =>
                {
                    b.Navigation("QrStuffs");
                });
#pragma warning restore 612, 618
        }
    }
}
