// <auto-generated />
using BarcodeScannerDatabaseImplement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarcodeScannerDatabaseImplement.Migrations
{
    [DbContext(typeof(BarcodeScannerDatabase))]
    partial class BarcodeScannerDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BarcodeScannerDatabaseImplement.Models.BarcodeProduct", b =>
                {
                    b.Property<long>("Gtin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Gtin");

                    b.ToTable("BarcodeProducts");
                });

            modelBuilder.Entity("BarcodeScannerDatabaseImplement.Models.QrStuff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Gtin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("QrStuffs");
                });
#pragma warning restore 612, 618
        }
    }
}
